### ISSUE TITLE
macOS 10.12 에서 libevent kq_init 에러 문제

### ISSUE THREAD

**Issue by whchoi83** [jam2in/arcus#1]
2016년 09월 20일에 OS X 가 macOS Sierra (10.12) 로 upgrade 됐습니다.
os 를 업그레이드 하고 나면 arcus-memcached 기동 시에 현재 ARCUS 에 포함되어 있는 libevent 에서 아래와 같은 에러가 발생됩니다.

```
[warn] kq_init: detected broken kqueue; not using.: Invalid argument
Done.
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
```

현재 libevent 2.1.6-beta 에는 패치되어있습니다. 
참고로 libevent 의 stable version 은 2.0.22입니다.

위 내용에 대한 commit 은 https://github.com/libevent/libevent/commit/df6f99e5b51a3c0786f54cb9822604ec63385400 에서 확인하시면 되며, 
ARCUS 에 포함된 libevent 를 직접 수정해서 build 후 arcus-memcached 를 기동하면 문제가 없습니다.

**Comment by jhpark816** [comment]
@whchoi83 
이 건은 우리가 결정하기 나름인 것 같은 데, 난 아래 순서가 좋은 것 같네요.
- arcus에 포함된 libevent 코드에 patch 적용
- libevent 2.1.6 이상이 stable 버전이 되면, arcus의 libevent 교체.
  - 이 경우, linux, mac os 모두 test 필요.

**Comment by whchoi83** [comment]
@jhpark816 
저도 현재로써는 그 방법이 제일 나은 것 같습니다.
2.1.6 으로 교체하는 경우에 deprecated 된 함수만 고려하면 될 것 같습니다.

**Comment by jhpark816** [comment]
@whchoi83 진행하시죠.

**Comment by whchoi83** [comment]
본 이슈는 close 하고 libevent 의 stable 버전이 2.1.6 이 되면 별도의 이슈로 진행하도록 하겠습니다.
